export const featureTypes: Record<string, string> = {
  PCLI: 'Country',
  ADM1: 'State / Region',
  ADM2: 'County / District',
  ADM3: 'Local District',
  ADM4: 'Municipality',
  PPL: 'City / Town',
  PPLA: 'Regional Capital',
  PPLC: 'Capital City',
  PPLL: 'Locality',
  PPLX: 'Neighbourhood',
  AIRP: 'Airport',
  HSP: 'Hospital',
  SCH: 'School',
  UNIV: 'University',
  MT: 'Mountain',
  PK: 'Peak',
  ISL: 'Island',
  STM: 'Stream',
  LK: 'Lake',
  BAY: 'Bay',
  PRK: 'Park',
  MALL: 'Shopping Centre',
  MUSE: 'Museum',
  HTL: 'Hotel',
  REST: 'Restaurant',
  NOM: 'Location',
};

export const featureClasses: Record<string, string> = {
  A: 'Administrative place',
  H: 'Water feature',
  L: 'Park or area',
  P: 'Populated place',
  R: 'Road or transport',
  S: 'Site or building',
  T: 'Mountain or landform',
  U: 'Undersea feature',
  V: 'Forest or vegetation',
};
